# src/solana_canister/Cargo.toml
[package]
name = "solana_canister"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
candid = "0.10"
ic-cdk = "0.13"
sol-rpc-client = { git = "https://github.com/dfinity/sol-rpc-canister.git", rev = "..." } # Use a specific commit hash
sol-rpc-types = { git = "https://github.com/dfinity/sol-rpc-canister.git", rev = "..." } # Use a specific commit hash
solana-pubkey = "2.0"
solana-hash = "2.0"
solana-message = "2.0"
solana-transaction = "2.0"
solana-system-interface = "2.0"
spl-associated-token-account-interface = "2.0"
solana-instruction = "2.0"
bs58 = "0.5"
num = "0.4"
serde = { version = "1.0", features = ["derive"] }
ic-ed25519 = "0.1"

[dev-dependencies]
candid_parser = "0.1"

[profile.release]
lto = true
opt-level = 'z'
strip = true
panic = "abort"
